//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::Transform3DParallax::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::Transform3DParallax::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->wideState = safe_cast<::Windows::UI::Xaml::VisualState^>(__target);
            }
            break;
        case 2:
            {
                this->narrowState = safe_cast<::Windows::UI::Xaml::VisualState^>(__target);
            }
            break;
        case 3:
            {
                this->Splitter = safe_cast<::Windows::UI::Xaml::Controls::SplitView^>(__target);
            }
            break;
        case 4:
            {
                ::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ element4 = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(element4))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Transform3DParallax::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button_Click);
            }
            break;
        case 5:
            {
                this->Hamburger = safe_cast<::Windows::UI::Xaml::Controls::FontIcon^>(__target);
            }
            break;
        case 6:
            {
                this->HeaderPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 7:
            {
                this->SampleTitle = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 8:
            {
                this->ScenarioControl = safe_cast<::Windows::UI::Xaml::Controls::ListBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ListBox^>(this->ScenarioControl))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::Transform3DParallax::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&MainPage::ScenarioControl_SelectionChanged);
            }
            break;
        case 9:
            {
                this->FooterPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 10:
            {
                this->Copyright = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 11:
            {
                this->LinksPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 12:
            {
                ::Windows::UI::Xaml::Controls::HyperlinkButton^ element12 = safe_cast<::Windows::UI::Xaml::Controls::HyperlinkButton^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::HyperlinkButton^>(element12))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Transform3DParallax::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Footer_Click);
            }
            break;
        case 13:
            {
                this->PrivacyLink = safe_cast<::Windows::UI::Xaml::Controls::HyperlinkButton^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::HyperlinkButton^>(this->PrivacyLink))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Transform3DParallax::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Footer_Click);
            }
            break;
        case 14:
            {
                this->WindowsLogo = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 15:
            {
                this->Header = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 16:
            {
                this->ScenarioFrame = safe_cast<::Windows::UI::Xaml::Controls::Frame^>(__target);
            }
            break;
        case 17:
            {
                this->StatusPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 18:
            {
                this->StatusLabel = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 19:
            {
                this->StatusBorder = safe_cast<::Windows::UI::Xaml::Controls::Border^>(__target);
            }
            break;
        case 20:
            {
                this->StatusBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::Transform3DParallax::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


