#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class ScrollViewer;
                ref class Image;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Media {
                namespace Media3D {
                    ref class PerspectiveTransform3D;
                }
            }
        }
    }
}

namespace Transform3DParallax
{
    partial ref class Scenario1_ParallaxBackground : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ RootGrid;
        private: ::Windows::UI::Xaml::Controls::ScrollViewer^ ParallaxRoot;
        private: ::Windows::UI::Xaml::Media::Media3D::PerspectiveTransform3D^ PerspectiveTransform;
        private: ::Windows::UI::Xaml::Controls::Image^ RainierBackgroundImage;
        private: ::Windows::UI::Xaml::Controls::Image^ CliffBackgroundImage;
    };
}

