//*********************************************************
//
// Copyright (c) Microsoft. All rights reserved.
// This code is licensed under the MIT License (MIT).
// THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
// IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
// PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
//
//*********************************************************
//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGen.exe
//   Version: 1.0.0
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Extension Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UAP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGen - Invoke the following command with a valid 
//   Introspection XML file:
//     AllJoynCodeGen -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace alljoyn { namespace Bus { namespace Samples { namespace Secure {

ref class SecureInterfaceConsumer;

public ref class SecureInterfaceCatResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property Platform::String^ OutStr
    {
        Platform::String^ get() { return m_interface_outStr; }
    internal:
        void set(_In_ Platform::String^ value) { m_interface_outStr = value; }
    }
    
    static SecureInterfaceCatResult^ CreateSuccessResult(_In_ Platform::String^ interface_outStr)
    {
        auto result = ref new SecureInterfaceCatResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->OutStr = interface_outStr;
        return result;
    }
    
    static SecureInterfaceCatResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new SecureInterfaceCatResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    Platform::String^ m_interface_outStr;
};

public ref class SecureInterfaceJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property SecureInterfaceConsumer^ Consumer
    {
        SecureInterfaceConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ SecureInterfaceConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    SecureInterfaceConsumer^ m_consumer;
};

} } } } } 
